[versions]
mod-version = "0.1.0"

# Fabric
jdk = "21"
minecraft = "1.21.1"
fabric-loader = "0.16.0"

# Loom
loom = "1.6.13"

# Meteor
meteor = "0.5.8"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
meteor-client = { module = "meteordevelopment:meteor-client", version.ref = "meteor" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
